version: '3.4'

services:
  firebase.origin:
    image: firebas.origin
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
